### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by inhahe** [Y4kuzi/ProvisionIRCd#7]
Would be nice if it worked on Windows =/

**Comment by Y4kuzi** [comment]
Hi,

Can you pull the latest commits and see if it works now?

**Comment by inhahe** [comment]
How can I disable SSL so I don't need  'server.cert.pem' and 'server.key.pem'?

**Comment by Y4kuzi** [comment]
Not sure why you would want that, since it will drastically drop your security.

First perform another git pull (I hadn't implemented this insecure feature before) and then open your ircd.conf.
In there you can specifcy which ports use SSL/TLS in the "listen" block.
Some ports have "ssl" listed under their "options", you can just remove or comment that single line.
Careful with doing so, since the configuration files are in JSON format and are pretty strict when it comes to syntax.

Let me know if there are any issues.

**Comment by inhahe** [comment]
Thanks for all your effort! I ended up just figuring out how to make those files, even though I don't really understand/know much about certificates. I didn't want to create those files because I thought I'd have to do some sort of request from an authority and maybe prove I'm me by putting some file on a domain or something and I think I've already requested a certificate before and I didn't want to do it multiple times (I figured one entity is supposed to have one certificate) and it just seemed like a big pain in the butt. ;p (and I always connect to IRC on port 6667 so I felt security was unimportant ;p) I made the cert using this http://slproweb.com/products/Win32OpenSSL.html (not sure if that's self-signed or not or what that means)

Anyway the program works, I connected to it locally using mIRC and joined a new channel. Thanks!

**Comment by Y4kuzi** [comment]
Glad to hear you got it working.

Self-signed certificates do a good enough job, but if you have a domain name you can use Let's Encrypt to obtain a free and valid certificate.
Each domain requires their separate certificate (they are checked to see if the domain matches the one in the certificate).

I am not sure about the process of obtaining a Let's Encrypt certificate on Windows, but it requires a webserver to confirm that you are the owner of the domain.
In case you ever want to look up on how to set one up, this link might be useful: https://certbot.eff.org/lets-encrypt/windows-other.html

Either way, with a self-signed certificate your cients' connections are also secure, but they might get a warning about an "invalid certificate" or something to that effect.
That is because your client does not know whether your certificate can be trusted or not. In this case, you can ignore this warning since you generated this certificate yourself.
